### ISSUE TITLE
Stat tracking organisms

### ISSUE THREAD

**Issue by Zediwan** [Zediwan/EvolutionSimulation#50]
These stats should be updated during an organisms life-span and could be

- [x] Amount of Plants eaten
- [x] Amount of Animals eaten
- [x] Amount of Animals attacked
- [x] Amount of offspring birthed
- [x] Distance covered

etc.

**Comment by Zediwan** [comment]
Implemented first batch of stats alongside their updates

**Comment by Zediwan** [comment]
Need to implement a way to see the stats
